version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://localhost:4000
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - ./backend/.env
    environment:
      - AI_SERVICE_URL=http://ai-service:5001
    depends_on:
      - mongodb
      - ai-service

  ai-service:
    platform: linux/arm64
    build:
      context: ./ai
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - ./ai/.env
    depends_on:
      - mongodb

  mongodb:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

volumes:
  mongodb_data: 